theme = "gruvbox-dark"
icons = "awesome"


# not working with flatpak spotify at the moment
#[[block]]
#block = "music"
#player = "spotify"
#buttons = ["play", "next"]

[[block]]
block = "uptime"

[[block]]
block = "net"
device = "wlp82s0"
format = "{ssid} {signal_strength} {ip}"
interval = 5
on_click = "alacritty -e nmtui"

#[[block]]
#block = "external_ip"
#format = "{ip} {city} {country_code}"

[[block]]
block = "disk_space"
path = "/home/"
alias = "~"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_free;M}/{mem_total;M}({mem_total_used_percents})"
format_swap = "{swap_free;M}/{swap_total;M}({swap_used_percents})"


[[block]]
block = "cpu"
interval = 1


[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "backlight"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 1
format = "%a %d-%m-%Y %H:%M:%S"


