theme = "plain"
icons = "awesome"


# not working with flatpak spotify at the moment
#[[block]]
#block = "music"
#buttons = ["play", "next"]

[[block]]
block = "net"
device = "wlp4s0"
ip = true
ssid = true
interval = 5
use_bits = false
signal_strength = true
speed_up = false
speed_down = false


[[block]]
block = "disk_space"
path = "/home/"
alias = "~"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1



[[block]]
block = "backlight"


[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 1
format = "%a %d-%m-%Y %H:%M:%S"


