[theme]
theme = "gruvbox-dark"
[icons]
icons = "awesome4"


# not working with flatpak spotify at the moment
[[block]]
block = "music"
format = " $combo.str(max_w:50,rot_interval:0.5 ) $prev $play $next |"
separator = " - "
#[block.theme_overrides]
#info_bg = "#98971a"

[[block]]
block = "uptime"
interval = 3600 # update every hour

[[block]]
block = "net"
device = "wlp82s0"
interval = 5
format = " $icon $signal_strength $ip "
missing_format = " x "
[[block.click]]
button = "left"
cmd = "alacritty -e nmtui"

#[[block]]
#block = "external_ip"
#format = "$ip $city $country_code"

[[block]]
block = "disk_space"
path = "/home/"
info_type = "available"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $available "
format_alt = " $icon $percentage "

[[block]]
block = "cpu"
format = "$icon $utilization"
interval = 1
[[block.click]]                                                                                                    
button = "left"
cmd = "alacritty -e htop"
    
#[[block]]
#block = "load"
#interval = 1
#format = "{1m}"

[[block]]
block = "backlight"

[[block]]
block = "battery"
format = " $icon $percentage {$time |}"
device = "DisplayDevice"
driver = "upower"
[[block.click]]                                                                                                        
button = "left"                                                                                                        
cmd = "/usr/bin/powerprofilesctl set balanced && notify-send Balanced"
[[block.click]]                                                                                                        
button = "right"
cmd = "/usr/bin/powerprofilesctl set power-saver && notify-send Power-Saver"
[[block.click]]                                                                                                        
button = "middle"
cmd = "/usr/bin/powerprofilesctl set performance && notify-send Performance"


[[block]]
block = "sound"
max_vol	= 100
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 1
format = "$timestamp.datetime(f:'%a %d-%m-%Y %H:%M:%S')"


